"""
Django settings for gameplay project.

Generated by 'django-admin startproject' using Django 5.2.11.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)6_y=2$b31cpccv)h*-kjznf19%m^5tq4ycp2)p3hsq#pfc(1l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    
    "http://localhost:8001",
    "http://localhost:8002",
    "http://127.0.0.1:8001",
    "http://127.0.0.1:8002",
]


# Application definition

INSTALLED_APPS = [
    'clips',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',                    # Add Cloudinary storage backend
    'cloudinary',                            # Add Cloudinary app for media management
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gameplay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gameplay.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Login redirect
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'clips.User'

# Pagination
CLIPS_PER_PAGE = 10


# CONFIGURACIÓN CLOUDINARY
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dazus8sgd',
    'API_KEY': '451383546856319',
    'API_SECRET': 'BcQIoOK_1Cz90YK5npj3uIn7iQ8',
}

# Esto le dice a Django dónde guardar los archivos por defecto
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'




# ---------------------------------------------------------
# CORRECCIÓN PARA EL ERROR "MUST SUPPLY API_KEY"
# Esto configura la librería base 'cloudinary' que usa models.py
# ---------------------------------------------------------
import cloudinary

cloudinary.config(
    cloud_name = 'dazus8sgd',
    api_key = '451383546856319',
    api_secret = 'BcQIoOK_1Cz90YK5npj3uIn7iQ8'
)
